/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IPriceOracle__factory } from "./IPriceOracle__factory";
export { IibToken__factory } from "./IibToken__factory";
